//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InformationCenterModel", "FK_FieldValue_DateTimeFieldValue", "FieldValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InformationCenter.Data.FieldValue), "DateTimeFieldValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(InformationCenter.Data.DateTimeFieldValue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InformationCenterModel", "FK_DocDescription_DocDocument", "Document", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InformationCenter.Data.Document), "DocDescription", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InformationCenter.Data.DocDescription))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InformationCenterModel", "FK_FieldValue_DocDescription", "DocDescription", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InformationCenter.Data.DocDescription), "FieldValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InformationCenter.Data.FieldValue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InformationCenterModel", "FK_Field_FieldType", "FieldType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InformationCenter.Data.FieldType), "Field", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InformationCenter.Data.Field))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InformationCenterModel", "FK_FieldTemplate_FieldType", "Field", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InformationCenter.Data.Field), "NNFieldTemplate", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InformationCenter.Data.NNFieldTemplate))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InformationCenterModel", "FK_FieldValue_Field", "Field", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InformationCenter.Data.Field), "FieldValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InformationCenter.Data.FieldValue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InformationCenterModel", "FK_FieldValue_FloatFieldValue", "FieldValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InformationCenter.Data.FieldValue), "FloatFieldValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(InformationCenter.Data.FloatFieldValue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InformationCenterModel", "FK_FieldValue_StringFieldValue", "FieldValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InformationCenter.Data.FieldValue), "StringFieldValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(InformationCenter.Data.StringFieldValue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InformationCenterModel", "FK_FieldTemplate_Template", "Template", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InformationCenter.Data.Template), "NNFieldTemplate", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InformationCenter.Data.NNFieldTemplate))]

// Original file name:
// Generation date: 26.04.2009 23:10:30
namespace InformationCenter.Data
{
    
    /// <summary>
    /// There are no comments for InformationCenterEntities in the schema.
    /// </summary>
    public partial class InformationCenterEntities : ObjectContextEx
    {
        /// <summary>
        /// Initializes a new InformationCenterEntities object using the connection string found in the 'InformationCenterEntities' section of the application configuration file.
        /// </summary>
        public InformationCenterEntities() : 
                base("name=InformationCenterEntities", "InformationCenterEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new InformationCenterEntities object.
        /// </summary>
        public InformationCenterEntities(string connectionString) : 
                base(connectionString, "InformationCenterEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new InformationCenterEntities object.
        /// </summary>
        public InformationCenterEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "InformationCenterEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for DateTimeFieldValue in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<DateTimeFieldValue> DateTimeFieldValue
        {
            get
            {
                if ((this._DateTimeFieldValue == null))
                {
                    this._DateTimeFieldValue = base.CreateQuery<DateTimeFieldValue>("[DateTimeFieldValue]");
                }
                return this._DateTimeFieldValue;
            }
        }
        private global::System.Data.Objects.ObjectQuery<DateTimeFieldValue> _DateTimeFieldValue;
        /// <summary>
        /// There are no comments for DocDescription in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<DocDescription> DocDescription
        {
            get
            {
                if ((this._DocDescription == null))
                {
                    this._DocDescription = base.CreateQuery<DocDescription>("[DocDescription]");
                }
                return this._DocDescription;
            }
        }
        private global::System.Data.Objects.ObjectQuery<DocDescription> _DocDescription;
        /// <summary>
        /// There are no comments for Document in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Document> Document
        {
            get
            {
                if ((this._Document == null))
                {
                    this._Document = base.CreateQuery<Document>("[Document]");
                }
                return this._Document;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Document> _Document;
        /// <summary>
        /// There are no comments for Field in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Field> Field
        {
            get
            {
                if ((this._Field == null))
                {
                    this._Field = base.CreateQuery<Field>("[Field]");
                }
                return this._Field;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Field> _Field;
        /// <summary>
        /// There are no comments for FieldType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FieldType> FieldType
        {
            get
            {
                if ((this._FieldType == null))
                {
                    this._FieldType = base.CreateQuery<FieldType>("[FieldType]");
                }
                return this._FieldType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FieldType> _FieldType;
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FieldValue> FieldValue
        {
            get
            {
                if ((this._FieldValue == null))
                {
                    this._FieldValue = base.CreateQuery<FieldValue>("[FieldValue]");
                }
                return this._FieldValue;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FieldValue> _FieldValue;
        /// <summary>
        /// There are no comments for FloatFieldValue in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FloatFieldValue> FloatFieldValue
        {
            get
            {
                if ((this._FloatFieldValue == null))
                {
                    this._FloatFieldValue = base.CreateQuery<FloatFieldValue>("[FloatFieldValue]");
                }
                return this._FloatFieldValue;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FloatFieldValue> _FloatFieldValue;
        /// <summary>
        /// There are no comments for NNFieldTemplate in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<NNFieldTemplate> NNFieldTemplate
        {
            get
            {
                if ((this._NNFieldTemplate == null))
                {
                    this._NNFieldTemplate = base.CreateQuery<NNFieldTemplate>("[NNFieldTemplate]");
                }
                return this._NNFieldTemplate;
            }
        }
        private global::System.Data.Objects.ObjectQuery<NNFieldTemplate> _NNFieldTemplate;
        /// <summary>
        /// There are no comments for StringFieldValue in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<StringFieldValue> StringFieldValue
        {
            get
            {
                if ((this._StringFieldValue == null))
                {
                    this._StringFieldValue = base.CreateQuery<StringFieldValue>("[StringFieldValue]");
                }
                return this._StringFieldValue;
            }
        }
        private global::System.Data.Objects.ObjectQuery<StringFieldValue> _StringFieldValue;
        /// <summary>
        /// There are no comments for Template in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Template> Template
        {
            get
            {
                if ((this._Template == null))
                {
                    this._Template = base.CreateQuery<Template>("[Template]");
                }
                return this._Template;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Template> _Template;
        /// <summary>
        /// There are no comments for DateTimeFieldValue in the schema.
        /// </summary>
        public void AddToDateTimeFieldValue(DateTimeFieldValue dateTimeFieldValue)
        {
            base.AddObject("DateTimeFieldValue", dateTimeFieldValue);
        }
        /// <summary>
        /// There are no comments for DocDescription in the schema.
        /// </summary>
        public void AddToDocDescription(DocDescription docDescription)
        {
            base.AddObject("DocDescription", docDescription);
        }
        /// <summary>
        /// There are no comments for Document in the schema.
        /// </summary>
        public void AddToDocument(Document document)
        {
            base.AddObject("Document", document);
        }
        /// <summary>
        /// There are no comments for Field in the schema.
        /// </summary>
        public void AddToField(Field field)
        {
            base.AddObject("Field", field);
        }
        /// <summary>
        /// There are no comments for FieldType in the schema.
        /// </summary>
        public void AddToFieldType(FieldType fieldType)
        {
            base.AddObject("FieldType", fieldType);
        }
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        public void AddToFieldValue(FieldValue fieldValue)
        {
            base.AddObject("FieldValue", fieldValue);
        }
        /// <summary>
        /// There are no comments for FloatFieldValue in the schema.
        /// </summary>
        public void AddToFloatFieldValue(FloatFieldValue floatFieldValue)
        {
            base.AddObject("FloatFieldValue", floatFieldValue);
        }
        /// <summary>
        /// There are no comments for NNFieldTemplate in the schema.
        /// </summary>
        public void AddToNNFieldTemplate(NNFieldTemplate nNFieldTemplate)
        {
            base.AddObject("NNFieldTemplate", nNFieldTemplate);
        }
        /// <summary>
        /// There are no comments for StringFieldValue in the schema.
        /// </summary>
        public void AddToStringFieldValue(StringFieldValue stringFieldValue)
        {
            base.AddObject("StringFieldValue", stringFieldValue);
        }
        /// <summary>
        /// There are no comments for Template in the schema.
        /// </summary>
        public void AddToTemplate(Template template)
        {
            base.AddObject("Template", template);
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.DateTimeFieldValue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="DateTimeFieldValue")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class DateTimeFieldValue : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new DateTimeFieldValue object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static DateTimeFieldValue CreateDateTimeFieldValue(global::System.Guid id)
        {
            DateTimeFieldValue dateTimeFieldValue = new DateTimeFieldValue();
            dateTimeFieldValue.ID = id;
            return dateTimeFieldValue;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Value;
        partial void OnValueChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_DateTimeFieldValue", "FieldValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public FieldValue FieldValue
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_DateTimeFieldValue", "FieldValue").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_DateTimeFieldValue", "FieldValue").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<FieldValue> FieldValueReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_DateTimeFieldValue", "FieldValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_DateTimeFieldValue", "FieldValue", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.DocDescription in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="DocDescription")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class DocDescription : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new DocDescription object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static DocDescription CreateDocDescription(global::System.Guid id, string name)
        {
            DocDescription docDescription = new DocDescription();
            docDescription.ID = id;
            docDescription.Name = name;
            return docDescription;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Document in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_DocDescription_DocDocument", "Document")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Document Document
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Document>("InformationCenterModel.FK_DocDescription_DocDocument", "Document").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Document>("InformationCenterModel.FK_DocDescription_DocDocument", "Document").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Document in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Document> DocumentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Document>("InformationCenterModel.FK_DocDescription_DocDocument", "Document");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Document>("InformationCenterModel.FK_DocDescription_DocDocument", "Document", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_DocDescription", "FieldValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<FieldValue> FieldValue
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<FieldValue>("InformationCenterModel.FK_FieldValue_DocDescription", "FieldValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<FieldValue>("InformationCenterModel.FK_FieldValue_DocDescription", "FieldValue", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.Document in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="Document")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Document : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Document object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="data">Initial value of Data.</param>
        public static Document CreateDocument(global::System.Guid id, byte[] data)
        {
            Document document = new Document();
            document.ID = id;
            document.Data = data;
            return document;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Data);
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        private byte[] _Data;
        partial void OnDataChanging(byte[] value);
        partial void OnDataChanged();
        /// <summary>
        /// There are no comments for DocDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_DocDescription_DocDocument", "DocDescription")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<DocDescription> DocDescription
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<DocDescription>("InformationCenterModel.FK_DocDescription_DocDocument", "DocDescription");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<DocDescription>("InformationCenterModel.FK_DocDescription_DocDocument", "DocDescription", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.Field in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="Field")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Field : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Field object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="text">Initial value of Text.</param>
        public static Field CreateField(global::System.Guid id, string text)
        {
            Field field = new Field();
            field.ID = id;
            field.Text = text;
            return field;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this.ReportPropertyChanging("Text");
                this._Text = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Text");
                this.OnTextChanged();
            }
        }
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        /// <summary>
        /// There are no comments for FieldType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_Field_FieldType", "FieldType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public FieldType FieldType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldType>("InformationCenterModel.FK_Field_FieldType", "FieldType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldType>("InformationCenterModel.FK_Field_FieldType", "FieldType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for FieldType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<FieldType> FieldTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldType>("InformationCenterModel.FK_Field_FieldType", "FieldType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<FieldType>("InformationCenterModel.FK_Field_FieldType", "FieldType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for NNFieldTemplate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldTemplate_FieldType", "NNFieldTemplate")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<NNFieldTemplate> NNFieldTemplate
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<NNFieldTemplate>("InformationCenterModel.FK_FieldTemplate_FieldType", "NNFieldTemplate");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<NNFieldTemplate>("InformationCenterModel.FK_FieldTemplate_FieldType", "NNFieldTemplate", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_Field", "FieldValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<FieldValue> FieldValue
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<FieldValue>("InformationCenterModel.FK_FieldValue_Field", "FieldValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<FieldValue>("InformationCenterModel.FK_FieldValue_Field", "FieldValue", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.FieldType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="FieldType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FieldType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new FieldType object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="sqlName">Initial value of SqlName.</param>
        /// <param name="nullable">Initial value of Nullable.</param>
        /// <param name="dotNetType">Initial value of DotNetType.</param>
        public static FieldType CreateFieldType(global::System.Guid id, string name, string sqlName, bool nullable, string dotNetType)
        {
            FieldType fieldType = new FieldType();
            fieldType.ID = id;
            fieldType.Name = name;
            fieldType.SqlName = sqlName;
            fieldType.Nullable = nullable;
            fieldType.DotNetType = dotNetType;
            return fieldType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property SqlName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SqlName
        {
            get
            {
                return this._SqlName;
            }
            set
            {
                this.OnSqlNameChanging(value);
                this.ReportPropertyChanging("SqlName");
                this._SqlName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SqlName");
                this.OnSqlNameChanged();
            }
        }
        private string _SqlName;
        partial void OnSqlNameChanging(string value);
        partial void OnSqlNameChanged();
        /// <summary>
        /// There are no comments for Property Nullable in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Nullable
        {
            get
            {
                return this._Nullable;
            }
            set
            {
                this.OnNullableChanging(value);
                this.ReportPropertyChanging("Nullable");
                this._Nullable = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Nullable");
                this.OnNullableChanged();
            }
        }
        private bool _Nullable;
        partial void OnNullableChanging(bool value);
        partial void OnNullableChanged();
        /// <summary>
        /// There are no comments for Property DotNetType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DotNetType
        {
            get
            {
                return this._DotNetType;
            }
            set
            {
                this.OnDotNetTypeChanging(value);
                this.ReportPropertyChanging("DotNetType");
                this._DotNetType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DotNetType");
                this.OnDotNetTypeChanged();
            }
        }
        private string _DotNetType;
        partial void OnDotNetTypeChanging(string value);
        partial void OnDotNetTypeChanged();
        /// <summary>
        /// There are no comments for Field in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_Field_FieldType", "Field")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Field> Field
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Field>("InformationCenterModel.FK_Field_FieldType", "Field");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Field>("InformationCenterModel.FK_Field_FieldType", "Field", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.FieldValue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="FieldValue")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FieldValue : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new FieldValue object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static FieldValue CreateFieldValue(global::System.Guid id)
        {
            FieldValue fieldValue = new FieldValue();
            fieldValue.ID = id;
            return fieldValue;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for DateTimeFieldValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_DateTimeFieldValue", "DateTimeFieldValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public DateTimeFieldValue DateTimeFieldValue
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<DateTimeFieldValue>("InformationCenterModel.FK_FieldValue_DateTimeFieldValue", "DateTimeFieldValue").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<DateTimeFieldValue>("InformationCenterModel.FK_FieldValue_DateTimeFieldValue", "DateTimeFieldValue").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for DateTimeFieldValue in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<DateTimeFieldValue> DateTimeFieldValueReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<DateTimeFieldValue>("InformationCenterModel.FK_FieldValue_DateTimeFieldValue", "DateTimeFieldValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<DateTimeFieldValue>("InformationCenterModel.FK_FieldValue_DateTimeFieldValue", "DateTimeFieldValue", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for DocDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_DocDescription", "DocDescription")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public DocDescription DocDescription
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<DocDescription>("InformationCenterModel.FK_FieldValue_DocDescription", "DocDescription").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<DocDescription>("InformationCenterModel.FK_FieldValue_DocDescription", "DocDescription").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for DocDescription in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<DocDescription> DocDescriptionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<DocDescription>("InformationCenterModel.FK_FieldValue_DocDescription", "DocDescription");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<DocDescription>("InformationCenterModel.FK_FieldValue_DocDescription", "DocDescription", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Field in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_Field", "Field")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Field Field
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Field>("InformationCenterModel.FK_FieldValue_Field", "Field").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Field>("InformationCenterModel.FK_FieldValue_Field", "Field").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Field in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Field> FieldReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Field>("InformationCenterModel.FK_FieldValue_Field", "Field");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Field>("InformationCenterModel.FK_FieldValue_Field", "Field", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for FloatFieldValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_FloatFieldValue", "FloatFieldValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public FloatFieldValue FloatFieldValue
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FloatFieldValue>("InformationCenterModel.FK_FieldValue_FloatFieldValue", "FloatFieldValue").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FloatFieldValue>("InformationCenterModel.FK_FieldValue_FloatFieldValue", "FloatFieldValue").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for FloatFieldValue in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<FloatFieldValue> FloatFieldValueReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FloatFieldValue>("InformationCenterModel.FK_FieldValue_FloatFieldValue", "FloatFieldValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<FloatFieldValue>("InformationCenterModel.FK_FieldValue_FloatFieldValue", "FloatFieldValue", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for StringFieldValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_StringFieldValue", "StringFieldValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public StringFieldValue StringFieldValue
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<StringFieldValue>("InformationCenterModel.FK_FieldValue_StringFieldValue", "StringFieldValue").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<StringFieldValue>("InformationCenterModel.FK_FieldValue_StringFieldValue", "StringFieldValue").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for StringFieldValue in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<StringFieldValue> StringFieldValueReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<StringFieldValue>("InformationCenterModel.FK_FieldValue_StringFieldValue", "StringFieldValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<StringFieldValue>("InformationCenterModel.FK_FieldValue_StringFieldValue", "StringFieldValue", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.FloatFieldValue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="FloatFieldValue")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FloatFieldValue : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new FloatFieldValue object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static FloatFieldValue CreateFloatFieldValue(global::System.Guid id)
        {
            FloatFieldValue floatFieldValue = new FloatFieldValue();
            floatFieldValue.ID = id;
            return floatFieldValue;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private global::System.Nullable<double> _Value;
        partial void OnValueChanging(global::System.Nullable<double> value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_FloatFieldValue", "FieldValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public FieldValue FieldValue
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_FloatFieldValue", "FieldValue").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_FloatFieldValue", "FieldValue").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<FieldValue> FieldValueReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_FloatFieldValue", "FieldValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_FloatFieldValue", "FieldValue", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.NNFieldTemplate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="NNFieldTemplate")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NNFieldTemplate : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new NNFieldTemplate object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static NNFieldTemplate CreateNNFieldTemplate(global::System.Guid id)
        {
            NNFieldTemplate nNFieldTemplate = new NNFieldTemplate();
            nNFieldTemplate.ID = id;
            return nNFieldTemplate;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Field in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldTemplate_FieldType", "Field")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Field Field
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Field>("InformationCenterModel.FK_FieldTemplate_FieldType", "Field").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Field>("InformationCenterModel.FK_FieldTemplate_FieldType", "Field").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Field in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Field> FieldReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Field>("InformationCenterModel.FK_FieldTemplate_FieldType", "Field");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Field>("InformationCenterModel.FK_FieldTemplate_FieldType", "Field", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Template in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldTemplate_Template", "Template")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Template Template
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Template>("InformationCenterModel.FK_FieldTemplate_Template", "Template").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Template>("InformationCenterModel.FK_FieldTemplate_Template", "Template").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Template in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Template> TemplateReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Template>("InformationCenterModel.FK_FieldTemplate_Template", "Template");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Template>("InformationCenterModel.FK_FieldTemplate_Template", "Template", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.StringFieldValue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="StringFieldValue")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class StringFieldValue : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new StringFieldValue object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static StringFieldValue CreateStringFieldValue(global::System.Guid id)
        {
            StringFieldValue stringFieldValue = new StringFieldValue();
            stringFieldValue.ID = id;
            return stringFieldValue;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldValue_StringFieldValue", "FieldValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public FieldValue FieldValue
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_StringFieldValue", "FieldValue").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_StringFieldValue", "FieldValue").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for FieldValue in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<FieldValue> FieldValueReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_StringFieldValue", "FieldValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<FieldValue>("InformationCenterModel.FK_FieldValue_StringFieldValue", "FieldValue", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InformationCenterModel.Template in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InformationCenterModel", Name="Template")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Template : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Template object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="creationDate">Initial value of CreationDate.</param>
        public static Template CreateTemplate(global::System.Guid id, string name, global::System.DateTime creationDate)
        {
            Template template = new Template();
            template.ID = id;
            template.Name = name;
            template.CreationDate = creationDate;
            return template;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CreationDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return this._CreationDate;
            }
            set
            {
                this.OnCreationDateChanging(value);
                this.ReportPropertyChanging("CreationDate");
                this._CreationDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreationDate");
                this.OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
        /// <summary>
        /// There are no comments for NNFieldTemplate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InformationCenterModel", "FK_FieldTemplate_Template", "NNFieldTemplate")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<NNFieldTemplate> NNFieldTemplate
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<NNFieldTemplate>("InformationCenterModel.FK_FieldTemplate_Template", "NNFieldTemplate");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<NNFieldTemplate>("InformationCenterModel.FK_FieldTemplate_Template", "NNFieldTemplate", value);
                }
            }
        }
    }
}
